#!/bin/bash
make clean
./generate_makefile.pl 10 > Makefile
#./random_matrix.pl 10 10 > a
#./random_matrix.pl 10 10 > b
cp ../../dist/Debug/GNU-Linux-x86/distributedmake .
time mpirun -x PATH=/home/palesana/makefiles/bin/:$PATH -hostfile ../../hosts distributedmake

